### ISSUE TITLE
Error in DebugDraw.DrawAABBInteranl (:1876)

### ISSUE THREAD

**Issue by Flavelius** [DmitriySalnikov/godot_debug_draw_cs#2]
GetDiagonalVectors must take box.End instead of box.Size as argument at :1879.
And DrawAABBInteranl is likely a typo too ('interanl' -> 'internal') btw.

**Comment by DmitriySalnikov** [comment]
> GetDiagonalVectors must take box.End instead of box.Size as argument at :1879.

hmm, that makes sense, but I don't see any visual changes.


> And DrawAABBInteranl is likely a typo too ('interanl' -> 'internal') btw.

there are many more 'interanl's' here :-)

**Comment by DmitriySalnikov** [comment]
> but I don't see any visual changes.

I checked it wrong. Now everything is fixed.
Thanks!
